const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.TileMovement,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.JavaScriptInEvents.FolhaJogo_Event11_Act4,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Flash.Acts.Flash,
		C3.JavaScriptInEvents.FolhaJogo_Event12_Act2,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{Sólido: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite: 0},
	{Sprite6: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite18: 0},
	{MovimentoEmGrid: 0},
	{Piscar: 0},
	{capi: 0},
	{Teclado: 0},
	{Sprite17: 0},
	{Sprite19: 0},
	{MoverPara: 0},
	{javali: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{uva: 0},
	{Sprite20: 0},
	{Texto: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite24: 0},
	{Mouse: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Texto2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{coracao: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	capi: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	javali: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	uva: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Texto2: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {}
}